### ISSUE TITLE
How to register adapters with jest-circus

### ISSUE THREAD

**Issue by stephenh** [gribnoysup/setup-polly-jest#23]
Hey; we've been using setup-polly-jest for awhile and it's working great, so thanks for the project!

We're trying to upgrade to jest 27 / jest-circus, and for some reason our adapters are no longer being registered, i.e. we have code like:

```
Polly.register(require("@pollyjs/adapter-node-http"));
Polly.register(require("@pollyjs/persister-fs"));
```

But our tests are now failing with:

```
    PollyError: [Polly] Adapter matching the name `node-http` was not registered.
```

I've put the new jest env at the top of our test files:

```
/** @jest-environment setup-polly-jest/jest-environment-node */
...
import "src/setupPolly";
...
describe("...", () => {
```

Where the `src/setupPolly` file is what has our common `Polly.register` code in it.

By adding some console.logs inside of polly itself, it looks like there are two versions of Polly's internal event emitter floating around, i.e. from a test run:

```
CREATED EventEmitter {
  madeAt: 1627748370545,
  [Symbol()]: Map { _c: Map(0) {} },
  [Symbol()]: Set { _c: Set(3) { 'register', 'create', 'stop' } }
}
  console.log
    CREATED EventEmitter {
      madeAt: 1627748375580,
      [Symbol()]: Map { _c: Map(0) {} },
      [Symbol()]: Set { _c: Set(3) { 'register', 'create', 'stop' } }
    }

      at Object.<anonymous> (node_modules/@pollyjs/core/dist/cjs/pollyjs-core.js:6195:9)

  console.log
    REGISTERING adapters

      at Object.<anonymous> (src/setupPolly.ts:10:9)

  console.log
    REGISTERING ON1 EventEmitter {
      madeAt: 1627748375580,
      [Symbol()]: Map { _c: Map(0) {} },
      [Symbol()]: Set { _c: Set(3) { 'register', 'create', 'stop' } }
    }

      at Function.on (node_modules/@pollyjs/core/src/polly.js:113:12)

  console.log
    REGISTERING ON1 EventEmitter {
      madeAt: 1627748375580,
      [Symbol()]: Map { _c: Map(1) { 'register' => [Set] } },
      [Symbol()]: Set { _c: Set(3) { 'register', 'create', 'stop' } }
    }

      at Function.on (node_modules/@pollyjs/core/src/polly.js:113:12)

EMITTING ON1 EventEmitter {
  madeAt: 1627748370545,
  [Symbol()]: Map { _c: Map(0) {} },
  [Symbol()]: Set { _c: Set(3) { 'register', 'create', 'stop' } }
}
INSIDE emitSync
INSIDE emitSync

  ● Test suite failed to run

    PollyError: [Polly] Adapter matching the name `node-http` was not registered.

      at Object.assert (node_modules/@pollyjs/utils/src/utils/assert.js:5:11)
      at Polly.connectTo (node_modules/@pollyjs/core/dist/cjs/pollyjs-core.js:6433:11)
      at node_modules/@pollyjs/core/src/polly.js:170:20
          at Array.forEach (<anonymous>)
      at Polly.configure (node_modules/@pollyjs/core/src/polly.js:170:20)
      at new Polly (node_modules/@pollyjs/core/dist/cjs/pollyjs-core.js:6221:10)
      at PollyEnvironmentNode.handleTestEvent (node_modules/setup-polly-jest/lib/jest-environment-polly.js:85:48)
```

What seems to be happening is:

* The `1627748370545` event emitter is created immediately when the test starts (I assume from the `jest-environment-node`)
* However a second `1627748375580` event emitter is also created (I assume this is due to Jest's sandboxing, like b/c our `src/setupPolly.ts` is imported from within our test, it is getting it's own separate require/vm context)
* Our `Polly.register(node-adapter)` call is putting the adapter into the 2nd / `1627748375580` emitter
  * You can see the 2nd event emitter's map is empty, but then starts to get populated i.e. ` 'register' => [Set]`
* But when `handleTestEvent` runs and tries to create a polly instance for the test, the `Polly.configure` is using the _first_ event emitter, `1627748370545` to look for adapters, and not finding any

So, that is what happening. I really don't know why though. :-) 

Is there a different way to `Polly.register` in the new jest-circus setup?

I've looked through the readme and the commit that added jest-circus support and didn't see anything obvious, but maybe I'm missing something.

Thanks!

**Comment by gribnoysup** [comment]
Hey @stephenh, thanks for reporting the issue! I can confirm that it exists and I think that you probably have the right idea about the root cause. I don't have time to immediately look into it, but will try to see if anything can be done to make global `Polly.register` calls work with the new jest runtime, I never used this way of registering adapters with polly, so when adding circus support I kinda missed that it's not working anymore. In the meantime as a workaround you can use the approach of directly passing adapters in the config as it is done in this tests in this repo:

https://github.com/gribnoysup/setup-polly-jest/blob/13db62ea1503b4ff61215f5a3c4d1bbd8de0d03d/test/integration/jest/index.test.js#L18-L26

**Comment by stephenh** [comment]
Ah great! We can definitely do that, and I confirmed that works for us as well.

Thanks for the quick reply!

**Comment by tonysamperi** [comment]
Hey guys sorry to bother, but I setup everything as documented, plus following the suggestion here...
But requests don't get intercepted...
I'm using Node 22 and the KikHttpService is using fetch underneath...
I have the impression that the "node-http" isn't actually used in these new environments?

**EDIT** 
I confirm that using `require("@pollyjs/adapter-fetch")` works instead. Silly, I didn't try earlier 😄.
Now interestingly enough I'm getting weird errors about the 204, but that's how my service works, it returns a 204 with an empty body.

**REEDIT**
Found the other one...Rightfully you assume everyone works as they should..

![image](https://github.com/user-attachments/assets/cb44c96b-f1ea-490b-9869-33b76d8e423b)

204 and empty response, while I was more flexible and wanted to handle the mediocrity of the average developer 😂😂😂
I will only test the 204 with empty 😄

Here's my test suite (updated after the first edit)

```typescript
/** @jest-environment setup-polly-jest/jest-environment-node */
import {KikHttpService, KikRestVerbs} from "@kikocosmeticsorg/uc-api-nest-common-fe";
import {resolve} from "path";
import {setupPolly} from "setup-polly-jest";

const localData = {
    urls: {
        emptyWithState: "/emptyWithState",
        empty: "/empty",
        foo: "/foo"
    }
};

describe("KikHttpService", () => {

    const pollyContext = setupPolly({
        adapters: [require("@pollyjs/adapter-fetch")],
        persister: require("@pollyjs/persister-fs"),
        persisterOptions: {
            fs: {
                recordingsDir: resolve(__dirname, "../__recordings__")
            }
        },
        mode: "record"
    });

    beforeEach(() => {
        pollyContext.polly.server.post(localData.urls.foo).intercept(async (_req_, res) => {
            res.status(200).send({
                foo: "bar"
            });
        });
        pollyContext.polly.server.get(localData.urls.empty).intercept(async (_req_, res) => {
            res.status(204).send({
                foo: "bar"
            });
        });
        pollyContext.polly.server.get(localData.urls.emptyWithState).intercept(async (_req_, res) => {
            res.status(200).send("");
        });
    });

    afterEach(() => pollyContext.polly.flush());

    it("should handle a post request with correct types", async () => {
        const response = await KikHttpService.$http<{ foo: "bar" }>({
            method: KikRestVerbs.POST,
            url: localData.urls.foo
        });
    });

    it("should merge query params correctly", async () => {
        const url = KikHttpService.mergeQueryParams("http://localhost:8080?foo=1&bar=2", {
            goo: "3",
            car: "4"
        });

        expect(url).toBe("http://localhost:8080/?foo=1&bar=2&goo=3&car=4");
    });

    it("should handle an empty response", async () => {
        const response = await KikHttpService.$http({
            method: "GET",
            url: localData.urls.empty
        });

        expect(response).toBe(null);
    });

    it("should treat 204 as empty response", async () => {
        const response = await KikHttpService.$http({
            method: "GET",
            url: localData.urls.emptyWithState
        });

        expect(response).toBe(null);
    });
});
```
