### ISSUE TITLE
TypeError: Class extends value #<Object> is not a constructor or null

### ISSUE THREAD

**Issue by guyellis** [gribnoysup/setup-polly-jest#31]
In a medium sized NodeJS project I upgraded the jest related dependencies from 27.x to 28.x

In 2 tests that I use `setup-polly-jest` I've started to run into this:

```
Test suite failed to run

    TypeError: Class extends value #<Object> is not a constructor or null

      at PollyEnvironmentFactory (node_modules/setup-polly-jest/lib/jest-environment-polly.js:63:41)
      at Object.<anonymous> (node_modules/setup-polly-jest/jest-environment-node.js:4:36)
      at Object.newLoader (node_modules/pirates/lib/index.js:141:7)
```

Both of these tests have the following preamble at the top:

```js
/**
 * @jest-environment setup-polly-jest/jest-environment-node
 */
```

**Comment by gribnoysup** [comment]
Thanks for reporting the issue. Should be fixed in 0.11.0
